services:
    books.block.category:
        class: BookBundle\Block\CategoryBlock
        arguments:
            - books.block.category
            - @templating
            - @doctrine
        tags:
            - { name: sonata.block }

    books.block.main_featured:
        class: BookBundle\Block\MainFeaturedBlock
        arguments:
            - books.block.main_featured
            - @templating
            - @doctrine
        tags:
            - { name: sonata.block }

    books.block.featured:
        class: BookBundle\Block\FeaturedBooksBlock
        arguments:
            - books.block.featured
            - @templating
            - @doctrine
        tags:
            - { name: sonata.block }