book_bundle.add_author:
    path:     /autor/adaugare
    defaults: { _controller: BookBundle:Author:add }
book_bundle.edit_author:
    path:     /autor/editare/{id}
    defaults: { _controller: BookBundle:Author:edit }
book_bundle.add_book:
    path: /carte/adaugare
    defaults: { _controller: BookBundle:Book:add }
book_bundle.edit_book:
    path: /carte/editare/{id}
    defaults: { _controller: BookBundle:Book:edit }
book_bundle.author_details:
    path: /autor/{slug_name}/{id}
    defaults: { _controller: BookBundle:Author:details }
book_bundle.author_list:
    path: /autor
    defaults: { _controller: BookBundle:Author:list }
