book_bundle.add_author:
    path:     /autor/adaugare
    defaults: { _controller: BookBundle:Author:add }
book_bundle.edit_author:
    path:     /autor/editare/{id}
    defaults: { _controller: BookBundle:Author:edit }
book_bundle.add_book:
    path: /carte/adaugare
    defaults: { _controller: BookBundle:Book:add }
book_bundle.edit_book:
    path: /carte/editare/{id}
    defaults: { _controller: BookBundle:Book:edit }
book_bundle.author_details:
    path: /autor/{slug_name}/{id}
    defaults: { _controller: BookBundle:Author:details }
book_bundle.author_list_page:
    path: /autori
    defaults: { _controller: BookBundle:Author:listPage }
book_bundle.category_details:
    path: /categorie/{slug_name}/{id}
    defaults: { _controller: BookBundle:Category:details }
book_bundle.show_book:
    path: /carte/{slug_name}/{id}
    defaults: { _controller: BookBundle:Book:showBook }
book_bundle.show_books:
    path: /carti
    defaults: { _controller: BookBundle:Book:showBooksPage}
