services:
    bookbundle.book_category_admin:
        class: BookBundle\Admin\CategoryAdmin
        arguments:
          - ~
          - BookBundle\Entity\Category
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, label: "Category", group: "Book" }
        calls:
          - [setTranslationDomain, [admin]]
          - [addChild, ['@bookbundle.subcategory_admin']]

    bookbundle.author_admin:
            class: BookBundle\Admin\AuthorAdmin
            arguments:
              - ~
              - BookBundle\Entity\Author
              - ~
            tags:
              - { name: sonata.admin, manager_type: orm, label: "Author", group: "Book" }
            calls:
              - [setTranslationDomain, [admin]]

    bookbundle.book_admin:
            class: BookBundle\Admin\BookAdmin
            arguments:
              - ~
              - BookBundle\Entity\Book
              - ~
            tags:
              - { name: sonata.admin, manager_type: orm, label: "Book", group: "Book" }
            calls:
              - [setTranslationDomain, [admin]]

    bookbundle.subcategory_admin:
            class: BookBundle\Admin\SubcategoryAdmin
            arguments:
              - ~
              - BookBundle\Entity\Subcategory
              - ~
            tags:
              - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
            calls:
              - [setTranslationDomain, [admin]]