imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ro

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"
    form:
            resources:
                - 'SonataCoreBundle:Form:datepicker.html.twig'
                - 'FrameworkExtensionBundle:Form:fields.html.twig'
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ UserBundle, AdminOverrideBundle, BookBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    assets:
        bootstrap_responsive:
            inputs:
                - libs/css/bootstrap-responsive.min.css
        bootstrap_min:
            inputs:
                - libs/css/bootstrap.min.css
        css_prettify:
            inputs:
                - libs/css/prettify.css
        font_awesome:
            inputs:
                - libs/css/font-awesome.css
        jquery:
            inputs:
                - libs/js/jquery.js
        bootshop:
            inputs:
                - libs/js/bootshop.js
        bootstrap_js:
            inputs:
                - libs/js/bootstrap.min.js
        jquery_lightbox:
            inputs:
                - libs/js/jquery.lightbox-0.5.js
        js_prettify:
            inputs:
                - libs/js/prettify.js


        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
      transport: smtp
      host:      mailtrap.io
      username:  d7f4302a44f825
      password:  5b02ff14e6bdaf
      auth_mode: cram-md5
      port: 2525
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User

# Sonata Admin Configuration
sonata_admin:
    title:                  'BookLand'
    options:
        pager_links: 10
        html5_validate: false
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        # default global templates
        user_block: AdminOverrideBundle:Block:block_user.html.twig
        layout:     AdminOverrideBundle::standard_layout.html.twig
        ajax:       SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }


sonata_block:
    default_contexts: [book_store]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        books.block.category:
        books.block.main_featured:
        books.block.featured:
        books.block.latest:
        static_pages.block.banners:

liip_imagine:
    resolvers:
        defaults:
            web_path: ~

    filter_sets:
        cache: ~

        # Below will be defined our image styles.
        avatar_profile_edit:
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        admin_show_avatar:
            filters:
                thumbnail: { size: [45, 45], mode: outbound }
        author_image_list:
            filters:
                thumbnail: { size: [175, 175], mode: outbound }
        book_list:
            filters:
                thumbnail: { size: [160, 160], mode: outbound }
        banner_list:
            filters:
                thumbnail: { size: [1170, 480], mode: outbound }
        author_list:
            filters:
                thumbnail: { size: [200, 160], mode: outbound }
        author_details_image:
            filters:
                thumbnail: { size: [270, 300], mode: outbound }
        show_image_book:
            filters:
                thumbnail: { size: [170, 250], mode: outbound }
        avatar_profile:
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
