add_comment:
    path:     /comments/add
    defaults: { _controller: ActivityBundle:Comment:addComment }
delete_comment:
    path:     /comments/delete
    defaults: { _controller: ActivityBundle:Comment:deleteComment }


