ActivityBundle\Entity\Like:
    type: entity
    table: likes
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: likes
            joinColumn:
              name: user_id
              referencedColumnName: id
        book:
            targetEntity: BookBundle\Entity\Book
            inversedBy: likes
            joinColumn:
              name: book_id
              referencedColumnName: id