BookBundle\Entity\Author:
    type: entity
    table: authors
    repositoryClass: BookBundle\Repository\AuthorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            nullable: false
            length: 255
        lastName:
            type: string
            nullable: false
            length: 255
        description:
            type: text
            nullable: true
        imageUrl:
            type: string
            nullable: false
            length: 255
        active:
            type: boolean
            nullable: false
    manyToOne:
        user:
          targetEntity: UserBundle\Entity\User
          inversedBy: authors
          joinColumn:
              name: user_id
              referencedColumnName: id
    manyToMany:
        books:
          targetEntity: BookBundle\Entity\Book
          mappedBy: authors
          nullable: true
