user_bundle.edit_profile:
    path:     /profile/edit
    defaults: { _controller: UserBundle:Profile:edit }
user_bundle.show_profile:
    path:     /profile/{id}
    defaults: { _controller: UserBundle:Profile:showProfile }
