services:
    static_pages.banner_admin:
        class: StaticPagesBundle\Admin\BannerAdmin
        arguments:
            - ~
            - StaticPagesBundle\Entity\Banner
            - ~
        tags:
          - { name: sonata.admin, manager_type: orm, label: "Banner", group: "Content management" }
        calls:
          - [setTranslationDomain, [admin]]
